<div style="border-radius: 10px; background-color: #112241">
    <h1 style="color: white; padding: 1rem"><b><span style='color:#8EDCE6'></span></b> Imports </b></h1>
</div>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pandas.plotting import parallel_coordinates
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import plotly.figure_factory as ff
from termcolor import colored
import datetime
import calendar

<div style="border-radius: 10px; background-color: #112241">
    <h1 style="color: white; padding: 1rem"><b><span style='color:#8EDCE6'></span></b> Analysis of Production </b></h1>
</div>

In [2]:
production = pd.read_csv('Updated/Production_Total.csv')
production.head()

Continent               Country         1980         1981         1982  \
0      Africa               Algeria  2.803017355   3.03753686  3.224933779   
1      Africa                Angola  0.335098042  0.291293691  0.276262403   
2      Africa                 Benin           in            0            0   
3      Africa              Botswana  0.008262057  0.008484744  0.009241913   
4      Africa          Burkina Faso            0            0            0   

          1983         1984         1985         1986         1987  ...  \
0  3.606400483  3.859176003  3.907465538  3.968324779  4.218086334  ...   
1  0.395407667  0.462550452  0.511269369  0.621432995  0.789428936  ...   
2      0.00896      0.01573      0.01793      0.01793      0.01569  ...   
3  0.008796519   0.00875198  0.009731845  0.010912138  0.010845329  ...   
4            0            0            0            0            0  ...   

          2013         2014         2015         2016         2017  \
0  6.510417691  6.561749872  6.696192523  6.910709728  6.830371007   
1  3.932204112  3.802528446  3.949946917   3.93529724  3.899020984   
2  0.000019082   0.00001902  0.000055914   0.00009232  0.000055278   
3  0.033334507  0.038240847  0.046562169    0.0419666  0.049654188   
4  0.001106756   0.00096051  0.000987814   0.00143096  0.001455654   

          2018         2019         2020         2021 Total_production  
0  6.755066467  6.474600013  5.972769931  6.656881917       238.118858  
1  3.814151292  3.526638469  3.159336901  2.824017641        90.852722  
2     4.64E-05     7.18E-05     6.19E-05     7.07E-05         0.178363  
3  0.048447799  0.047231633  0.041991759  0.044392707         0.952582  
4  0.002066608   0.00190567  0.001859876  0.002054882         0.033589  

[5 rows x 45 columns]

In [3]:
top_production = production[['Country', 'Total_production']].sort_values(by=['Total_production'], ascending=False).head(10)
# top_production.head(10)

fig = px.bar(top_production, x='Country', y='Total_production',labels={
                     "Country": "Countries",
                     "Total_production": "Total Production"
                 },title='Top 10 Countries with the Highest Energy Production:', width=1500, height=700)
fig.show()

In [4]:
continent_production =  production.groupby(by='Continent')['Total_production'].sum()
print(continent_production)

fig = px.pie(production, values='Total_production', names='Continent',color='Continent',
             title='Continent-wise total production of the World',
             width=1500, height=700)
fig.show()

Continent
    Africa                     1136.607828
    Asia & Oceania             4513.091785
    Central & South America    1007.329117
    Eurasia                    2871.262313
    Europe                     2006.767697
    Middle East                2416.979487
    North America              4203.165946
Name: Total_production, dtype: float64


In [5]:
top_production1 = production[['Country', 'Total_production']].sort_values(by=['Total_production'], ascending=False).head(10)
top_production2 = production[production.Country.isin(top_production1['Country'].unique())].sort_values(by=['Total_production'], ascending=False).head(10)
top_production2 = top_production2.T
top_production2.drop(['Country', 'Total_production', 'Continent'], axis=0, inplace=True)
top_production2.index.name = 'Year'
top_production2.columns = top_production1['Country'].values
# top_production2.head()
top_production3 = top_production2.replace('--', 0)
top_production4 = top_production3.astype(float).round(2)
# top_production4.head(5)

fig = px.line(top_production4, x = top_production4.index, y= top_production4.columns[0:],labels={
                     "Year": "Year",
                     "value": "Production Rate"}, title='Production Rates of top 5 Countries',width=1500, height=700)
fig.show()

In [6]:
coal_production = pd.read_csv('Updated/Production_Coal.csv')
NaturalGas_production = pd.read_csv('Updated/Production_NaturalGas.csv')
Neuclear_production = pd.read_csv('Updated/Production_NuclearTot.csv')
Petrolium_production = pd.read_csv('Updated/Production_Pertroleum.csv')

In [7]:
coal = coal_production[['Country', 'Production_Coal', 'Continent']].sort_values(by=['Production_Coal'], ascending=False)
coal.head()
coal = coal.head(5)
print(colored('Top 5 Countries producing energy from Coal: ', attrs=['bold']))
print('-------'*6)
coal.head()

Top 5 Countries producing energy from Coal: 
------------------------------------------


Country  Production_Coal       Continent
65                   China      1968.375434  Asia & Oceania
171          United States       852.874029   North America
59               Australia       299.184514  Asia & Oceania
72                   India       268.006024  Asia & Oceania
225                 Russia       219.834019         Eurasia

In [8]:
naturalGas = NaturalGas_production[['Country', 'Production_NaturalGas', 'Continent']].sort_values(by=['Production_NaturalGas'], ascending=False)
naturalGas.head()
naturalGas = naturalGas.head(5)
print(colored('Top 5 Countries producing energy from Natural Gas: ', attrs=['bold']))
print('-------'*7)
naturalGas.head()

Top 5 Countries producing energy from Natural Gas: 
-------------------------------------------------


Country  Production_NaturalGas      Continent
171            United States             908.316551  North America
225                   Russia             657.498874        Eurasia
220          Former U.S.S.R.             279.889259        Eurasia
166                   Canada             220.966536  North America
107                     Iran             141.525437    Middle East

In [9]:
neuclear = Neuclear_production[['Country', 'Production_Neuclear', 'Continent']].sort_values(by=['Production_Neuclear'], ascending=False)
neuclear.head()
neuclear = neuclear.head(5)
print(colored('Top 5 Countries producing energy from Neuclear resources: ', attrs=['bold']))
print('-------'*8)
neuclear.head()

Top 5 Countries producing energy from Neuclear resources: 
--------------------------------------------------------


Country  Production_Neuclear                Continent
171          United States           599.708904            North America
65                   China           263.671150           Asia & Oceania
166                 Canada           184.435834            North America
187                 France           179.762810                   Europe
127                 Brazil           149.166042  Central & South America

In [10]:
petrolium = Petrolium_production[['Country', 'Production_Petrolium', 'Continent']].sort_values(by=['Production_Petrolium'], ascending=False)
petrolium.head()
petrolium = petrolium.head(5)
print(colored('Top 5 Countries producing energy from Petrolium: ', attrs=['bold']))
print('-------'*7)
petrolium.head()

Top 5 Countries producing energy from Petrolium: 
-------------------------------------------------


Country  Production_Petrolium      Continent
116             Saudi Arabia            812.676836    Middle East
171            United States            788.120931  North America
225                   Russia            572.381872        Eurasia
220          Former U.S.S.R.            306.581247        Eurasia
107                     Iran            305.128101    Middle East

In [11]:
fig = make_subplots(rows=2, cols=2, subplot_titles=("Coal", "Natural Gas", "Neuclear Resources", "Petrolium"))

fig.add_trace(
    go.Bar(x=coal.Country, y=coal.Production_Coal),
                 row=1, col=1
)
fig.add_trace(
    go.Bar(x=naturalGas.Country, y=naturalGas.Production_NaturalGas),
                 row=1, col=2
)
fig.add_trace(
    go.Bar(x=neuclear.Country, y=neuclear.Production_Neuclear),
                 row=2, col=1
)
fig.add_trace(
    go.Bar(x=petrolium.Country, y=petrolium.Production_Petrolium),
                 row=2, col=2
)

fig.update_layout(height=1000, width=1500, title_text="Analysis of Production from Natural Resources")
fig.show()

<div style="border-radius: 10px; background-color: #112241">
    <h1 style="color: white; padding: 1rem"><b><span style='color:#8EDCE6'></span></b> Time Series Analysis of Production </b></h1>
</div>

#### <b>1 <span style='color:#8EDCE6'>|</span> Data Preprocessing </b>

In [12]:
data = pd.read_csv('Updated/Primary_Energy_Overview.csv')
data.head()

Month  Total Fossil Fuels Production  \
0   1973 January                       4.932632   
1  1973 February                       4.729582   
2     1973 March                       4.946902   
3     1973 April                       4.716271   
4       1973 May                       4.956995   

   Nuclear Electric Power Production  Total Renewable Energy Production  \
0                           0.068103                           0.403981   
1                           0.064634                           0.360900   
2                           0.072494                           0.400161   
3                           0.064070                           0.380470   
4                           0.062111                           0.392141   

   Total Primary Energy Production  Primary Energy Imports  \
0                         5.404715                1.173080   
1                         5.155115                1.168005   
2                         5.419556                1.309473   
3                         5.160812                1.085169   
4                         5.411246                1.162804   

   Primary Energy Exports  Primary Energy Net Imports  \
0                0.125781                    1.047299   
1                0.120883                    1.047122   
2                0.139950                    1.169523   
3                0.194185                    0.890984   
4                0.196775                    0.966029   

   Primary Energy Stock Change and Other  Total Fossil Fuels Consumption  \
0                               0.771858                        6.747651   
1                               0.390129                        6.163095   
2                              -0.067640                        6.044647   
3                              -0.110067                        5.493184   
4                              -0.305335                        5.613551   

   Nuclear Electric Power Consumption  Total Renewable Energy Consumption  \
0                            0.068103                            0.403981   
1                            0.064634                            0.360900   
2                            0.072494                            0.400161   
3                            0.064070                            0.380470   
4                            0.062111                            0.392141   

   Total Primary Energy Consumption  
0                          7.223873  
1                          6.592366  
2                          6.521439  
3                          5.941729  
4                          6.071940

In [13]:
data['Year'], data['Month'] = data['Month'].str.split(' ').str
# data.head()

C:\Users\HP\AppData\Local\Temp\ipykernel_15840\1031241722.py:1: FutureWarning:

Columnar iteration over characters will be deprecated in future releases.



In [14]:
months = {
        'January': '01',
        'February': '02',
        'March': '03',
        'April': '04',
         'May': '05',
         'June': '06',
         'July': '07',
         'August': '08',
         'September': '09',
         'October': '10',
         'November': '11',
         'December': '12'
        }

In [15]:
data2 = data.replace({"Month": months})
data2.head()

Month  Total Fossil Fuels Production  Nuclear Electric Power Production  \
0    01                       4.932632                           0.068103   
1    02                       4.729582                           0.064634   
2    03                       4.946902                           0.072494   
3    04                       4.716271                           0.064070   
4    05                       4.956995                           0.062111   

   Total Renewable Energy Production  Total Primary Energy Production  \
0                           0.403981                         5.404715   
1                           0.360900                         5.155115   
2                           0.400161                         5.419556   
3                           0.380470                         5.160812   
4                           0.392141                         5.411246   

   Primary Energy Imports  Primary Energy Exports  Primary Energy Net Imports  \
0                1.173080                0.125781                    1.047299   
1                1.168005                0.120883                    1.047122   
2                1.309473                0.139950                    1.169523   
3                1.085169                0.194185                    0.890984   
4                1.162804                0.196775                    0.966029   

   Primary Energy Stock Change and Other  Total Fossil Fuels Consumption  \
0                               0.771858                        6.747651   
1                               0.390129                        6.163095   
2                              -0.067640                        6.044647   
3                              -0.110067                        5.493184   
4                              -0.305335                        5.613551   

   Nuclear Electric Power Consumption  Total Renewable Energy Consumption  \
0                            0.068103                            0.403981   
1                            0.064634                            0.360900   
2                            0.072494                            0.400161   
3                            0.064070                            0.380470   
4                            0.062111                            0.392141   

   Total Primary Energy Consumption  Year  
0                          7.223873  1973  
1                          6.592366  1973  
2                          6.521439  1973  
3                          5.941729  1973  
4                          6.071940  1973

In [16]:
data2['Month'] = data2['Month'].map(str)
data2['Year'] = data2['Year'].map(str)
data2

Month  Total Fossil Fuels Production  Nuclear Electric Power Production  \
0      01                       4.932632                           0.068103   
1      02                       4.729582                           0.064634   
2      03                       4.946902                           0.072494   
3      04                       4.716271                           0.064070   
4      05                       4.956995                           0.062111   
..    ...                            ...                                ...   
595    08                       7.047525                           0.718526   
596    09                       6.915201                           0.664673   
597    10                       7.126618                           0.614741   
598    11                       6.875368                           0.647029   
599    12                       6.838495                           0.720583   

     Total Renewable Energy Production  Total Primary Energy Production  \
0                             0.403981                         5.404715   
1                             0.360900                         5.155115   
2                             0.400161                         5.419556   
3                             0.380470                         5.160812   
4                             0.392141                         5.411246   
..                                 ...                              ...   
595                           1.044026                         8.810077   
596                           0.978647                         8.558521   
597                           1.019209                         8.760568   
598                           1.097519                         8.619915   
599                           1.086509                         8.645586   

     Primary Energy Imports  Primary Energy Exports  \
0                  1.173080                0.125781   
1                  1.168005                0.120883   
2                  1.309473                0.139950   
3                  1.085169                0.194185   
4                  1.162804                0.196775   
..                      ...                     ...   
595                1.821828                2.327090   
596                1.702048                2.219831   
597                1.767733                2.322475   
598                1.761697                2.305923   
599                1.796398                2.416155   

     Primary Energy Net Imports  Primary Energy Stock Change and Other  \
0                      1.047299                               0.771858   
1                      1.047122                               0.390129   
2                      1.169523                              -0.067640   
3                      0.890984                              -0.110067   
4                      0.966029                              -0.305335   
..                          ...                                    ...   
595                   -0.505262                               0.225628   
596                   -0.517784                              -0.257997   
597                   -0.554743                              -0.394651   
598                   -0.544226                               0.210202   
599                   -0.619757                               1.054346   

     Total Fossil Fuels Consumption  Nuclear Electric Power Consumption  \
0                          6.747651                            0.068103   
1                          6.163095                            0.064634   
2                          6.044647                            0.072494   
3                          5.493184                            0.064070   
4                          5.613551                            0.062111   
..                              ...                                 ...   
595                        6.755154                            0.718526   
596 

In [17]:
df = data2[:-1]
df

Month  Total Fossil Fuels Production  Nuclear Electric Power Production  \
0      01                       4.932632                           0.068103   
1      02                       4.729582                           0.064634   
2      03                       4.946902                           0.072494   
3      04                       4.716271                           0.064070   
4      05                       4.956995                           0.062111   
..    ...                            ...                                ...   
594    07                       6.921426                           0.718109   
595    08                       7.047525                           0.718526   
596    09                       6.915201                           0.664673   
597    10                       7.126618                           0.614741   
598    11                       6.875368                           0.647029   

     Total Renewable Energy Production  Total Primary Energy Production  \
0                             0.403981                         5.404715   
1                             0.360900                         5.155115   
2                             0.400161                         5.419556   
3                             0.380470                         5.160812   
4                             0.392141                         5.411246   
..                                 ...                              ...   
594                           1.132400                         8.771935   
595                           1.044026                         8.810077   
596                           0.978647                         8.558521   
597                           1.019209                         8.760568   
598                           1.097519                         8.619915   

     Primary Energy Imports  Primary Energy Exports  \
0                  1.173080                0.125781   
1                  1.168005                0.120883   
2                  1.309473                0.139950   
3                  1.085169                0.194185   
4                  1.162804                0.196775   
..                      ...                     ...   
594                1.907862                2.294320   
595                1.821828                2.327090   
596                1.702048                2.219831   
597                1.767733                2.322475   
598                1.761697                2.305923   

     Primary Energy Net Imports  Primary Energy Stock Change and Other  \
0                      1.047299                               0.771858   
1                      1.047122                               0.390129   
2                      1.169523                              -0.067640   
3                      0.890984                              -0.110067   
4                      0.966029                              -0.305335   
..                          ...                                    ...   
594                   -0.386458                               0.199327   
595                   -0.505262                               0.225628   
596                   -0.517784                              -0.257997   
597                   -0.554743                              -0.394651   
598                   -0.544226                               0.210202   

     Total Fossil Fuels Consumption  Nuclear Electric Power Consumption  \
0                          6.747651                            0.068103   
1                          6.163095                            0.064634   
2                          6.044647                            0.072494   
3                          5.493184                            0.064070   
4                          5.613551                            0.062111   
..                              ...                                 ...   
594                        6.736891                            0.718109   
595 

In [18]:
date_1 ='{}-{}'.format(df['Month'].iloc[0], df['Year'].iloc[0])
date_2 = '{}-{}'.format('December', df['Year'].iloc[598])

df.index = pd.date_range(date_1, date_2, freq='M')
df.head()

Month  Total Fossil Fuels Production  \
1973-01-31    01                       4.932632   
1973-02-28    02                       4.729582   
1973-03-31    03                       4.946902   
1973-04-30    04                       4.716271   
1973-05-31    05                       4.956995   

            Nuclear Electric Power Production  \
1973-01-31                           0.068103   
1973-02-28                           0.064634   
1973-03-31                           0.072494   
1973-04-30                           0.064070   
1973-05-31                           0.062111   

            Total Renewable Energy Production  \
1973-01-31                           0.403981   
1973-02-28                           0.360900   
1973-03-31                           0.400161   
1973-04-30                           0.380470   
1973-05-31                           0.392141   

            Total Primary Energy Production  Primary Energy Imports  \
1973-01-31                         5.404715                1.173080   
1973-02-28                         5.155115                1.168005   
1973-03-31                         5.419556                1.309473   
1973-04-30                         5.160812                1.085169   
1973-05-31                         5.411246                1.162804   

            Primary Energy Exports  Primary Energy Net Imports  \
1973-01-31                0.125781                    1.047299   
1973-02-28                0.120883                    1.047122   
1973-03-31                0.139950                    1.169523   
1973-04-30                0.194185                    0.890984   
1973-05-31                0.196775                    0.966029   

            Primary Energy Stock Change and Other  \
1973-01-31                               0.771858   
1973-02-28                               0.390129   
1973-03-31                              -0.067640   
1973-04-30                              -0.110067   
1973-05-31                              -0.305335   

            Total Fossil Fuels Consumption  \
1973-01-31                        6.747651   
1973-02-28                        6.163095   
1973-03-31                        6.044647   
1973-04-30                        5.493184   
1973-05-31                        5.613551   

            Nuclear Electric Power Consumption  \
1973-01-31                            0.068103   
1973-02-28                            0.064634   
1973-03-31                            0.072494   
1973-04-30                            0.064070   
1973-05-31                            0.062111   

            Total Renewable Energy Consumption  \
1973-01-31                            0.403981   
1973-02-28                            0.360900   
1973-03-31                            0.400161   
1973-04-30                            0.380470   
1973-05-31                            0.392141   

            Total Primary Energy Consumption  Year  
1973-01-31                          7.223873  1973  
1973-02-28                          6.592366  1973  
1973-03-31                          6.521439  1973  
1973-04-30                          5.941729  1973  
1973-05-31                          6.071940  1973

In [19]:
data3 = df.drop(['Year', 'Month'], axis=1)
data3 = data3.rename_axis('Date')
data3.head()

Total Fossil Fuels Production  Nuclear Electric Power Production  \
Date                                                                           
1973-01-31                       4.932632                           0.068103   
1973-02-28                       4.729582                           0.064634   
1973-03-31                       4.946902                           0.072494   
1973-04-30                       4.716271                           0.064070   
1973-05-31                       4.956995                           0.062111   

            Total Renewable Energy Production  \
Date                                            
1973-01-31                           0.403981   
1973-02-28                           0.360900   
1973-03-31                           0.400161   
1973-04-30                           0.380470   
1973-05-31                           0.392141   

            Total Primary Energy Production  Primary Energy Imports  \
Date                                                                  
1973-01-31                         5.404715                1.173080   
1973-02-28                         5.155115                1.168005   
1973-03-31                         5.419556                1.309473   
1973-04-30                         5.160812                1.085169   
1973-05-31                         5.411246                1.162804   

            Primary Energy Exports  Primary Energy Net Imports  \
Date                                                             
1973-01-31                0.125781                    1.047299   
1973-02-28                0.120883                    1.047122   
1973-03-31                0.139950                    1.169523   
1973-04-30                0.194185                    0.890984   
1973-05-31                0.196775                    0.966029   

            Primary Energy Stock Change and Other  \
Date                                                
1973-01-31                               0.771858   
1973-02-28                               0.390129   
1973-03-31                              -0.067640   
1973-04-30                              -0.110067   
1973-05-31                              -0.305335   

            Total Fossil Fuels Consumption  \
Date                                         
1973-01-31                        6.747651   
1973-02-28                        6.163095   
1973-03-31                        6.044647   
1973-04-30                        5.493184   
1973-05-31                        5.613551   

            Nuclear Electric Power Consumption  \
Date                                             
1973-01-31                            0.068103   
1973-02-28                            0.064634   
1973-03-31                            0.072494   
1973-04-30                            0.064070   
1973-05-31                            0.062111   

            Total Renewable Energy Consumption  \
Date                                             
1973-01-31                            0.403981   
1973-02-28                            0.360900   
1973-03-31                            0.400161   
1973-04-30                            0.380470   
1973-05-31                            0.392141   

            Total Primary Energy Consumption  
Date                                          
1973-01-31                          7.223873  
1973-02-28                          6.592366  
1973-03-31                          6.521439  
1973-04-30                          5.941729  
1973-05-31                          6.071940

In [20]:
total_production0 = data3.filter(['Total Primary Energy Production'], axis=1)
total_production = total_production0.rename(columns={'Total Primary Energy Production':'Total_Production'})
total_production.head()

Total_Production
Date                        
1973-01-31          5.404715
1973-02-28          5.155115
1973-03-31          5.419556
1973-04-30          5.160812
1973-05-31          5.411246

In [21]:
fig = px.line(total_production, x = total_production.index, y= total_production.Total_Production,labels={
                     "Month": "Month",
                     "value": "Production Rate"}, title='Global Energy Production Rate',width=1500, height=800)
fig.show()

In [22]:
from statsmodels.tsa.seasonal import seasonal_decompose
results = seasonal_decompose(total_production['Total_Production'])

fig_1 = px.line(y=results.observed, x=results.observed.index, title='Observed',width=1500)
fig_1.show()

In [23]:
fig_2 = px.line(y=results.trend, x=results.trend.index, title='Trend',width=1500)
fig_2.show()

In [24]:
fig_2 = px.line(y=results.seasonal, x=results.seasonal.index, title='Seasonality',width=1500)
fig_2.show()

In [25]:
fig_2 = px.line(y=results.resid, x=results.resid.index, title='Residual',width=1500)
fig_2.show()

In [26]:
train = total_production[:-20]
test = total_production[-20:]
print(train.shape, test.shape)

(579, 1) (20, 1)


<div style="border-radius: 10px; background-color: #112241">
    <h1 style="color: white; padding: 1rem"><b><span style='color:#8EDCE6'></span></b> Auto Regression Model </b></h1>
</div>

In [27]:
from statsmodels.tsa.ar_model import AutoReg

In [28]:
autoreg_model = AutoReg(train, lags=10).fit()
print(autoreg_model.summary())

                            AutoReg Model Results                             
Dep. Variable:       Total_Production   No. Observations:                  579
Model:                    AutoReg(10)   Log Likelihood                  85.050
Method:               Conditional MLE   S.D. of innovations              0.208
Date:                Sat, 29 Apr 2023   AIC                           -146.100
Time:                        11:59:47   BIC                            -93.974
Sample:                    11-30-1973   HQIC                          -125.760
                         - 03-31-2021                                         
                           coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------
const                    0.0190      0.071      0.267      0.789      -0.120       0.158
Total_Production.L1      0.2684      0.042      6.354      0.000       0.186       0.351
Total_Produc

In [29]:
pred_auto = autoreg_model.predict(start = len(train), end = len(total_production)-1, dynamic=False)
# print(pred_auto)

In [30]:
fig = px.line(test['Total_Production'], width=1500)
fig.add_scatter(x=test.index, y=pred_auto, name='Predictions')
fig.show()

In [31]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, accuracy_score

print('Mean Squared Error: ', mean_squared_error(test['Total_Production'], pred_auto))

Mean Squared Error:  0.3566408009962111


<div style="border-radius: 10px; background-color: #112241">
    <h1 style="color: white; padding: 1rem"><b><span style='color:#8EDCE6'></span></b> Arima Model </b></h1>
</div>

In [32]:
from pmdarima import auto_arima
import warnings
warnings.filterwarnings("ignore")

In [33]:
stepwise_fit = auto_arima(total_production['Total_Production'], trace=True, suppress_warnings=True)
stepwise_fit.summary()

Performing stepwise search to minimize aic
 ARIMA(2,1,2)(0,0,0)[0] intercept   : AIC=-49.866, Time=1.14 sec
 ARIMA(0,1,0)(0,0,0)[0] intercept   : AIC=320.634, Time=0.10 sec
 ARIMA(1,1,0)(0,0,0)[0] intercept   : AIC=21.685, Time=0.14 sec
 ARIMA(0,1,1)(0,0,0)[0] intercept   : AIC=-23.479, Time=0.29 sec
 ARIMA(0,1,0)(0,0,0)[0]             : AIC=318.808, Time=0.14 sec
 ARIMA(1,1,2)(0,0,0)[0] intercept   : AIC=-49.992, Time=0.72 sec
 ARIMA(0,1,2)(0,0,0)[0] intercept   : AIC=-44.048, Time=0.50 sec
 ARIMA(1,1,1)(0,0,0)[0] intercept   : AIC=-50.918, Time=0.44 sec
 ARIMA(2,1,1)(0,0,0)[0] intercept   : AIC=-51.405, Time=0.51 sec
 ARIMA(2,1,0)(0,0,0)[0] intercept   : AIC=-29.629, Time=0.15 sec
 ARIMA(3,1,1)(0,0,0)[0] intercept   : AIC=-51.313, Time=0.57 sec
 ARIMA(3,1,0)(0,0,0)[0] intercept   : AIC=-28.882, Time=0.26 sec
 ARIMA(3,1,2)(0,0,0)[0] intercept   : AIC=-86.425, Time=1.38 sec
 ARIMA(4,1,2)(0,0,0)[0] intercept   : AIC=-143.118, Time=1.34 sec
 ARIMA(4,1,1)(0,0,0)[0] intercept   : AIC=-139.

<class 'statsmodels.iolib.summary.Summary'>
"""
                               SARIMAX Results                                
==============================================================================
Dep. Variable:                      y   No. Observations:                  599
Model:               SARIMAX(3, 1, 3)   Log Likelihood                 151.658
Date:                Sat, 29 Apr 2023   AIC                           -287.317
Time:                        12:00:10   BIC                           -252.168
Sample:                    01-31-1973   HQIC                          -273.632
                         - 11-30-2022                                         
Covariance Type:                  opg                                         
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
intercept      0.0182      0.008      2.301      0.021       0.003       0.034
ar.L1         -1.4432      0.054    -26.530      0.000      -1.550      -1.337
ar.L2         -0.5066      0.094     -5.377      0.000      -0.691      -0.322
ar.L3          0.2809      0.054      5.188      0.000       0.175       0.387
ma.L1          0.8970      0.044     20.470      0.000       0.811       0.983
ma.L2         -0.3331      0.059     -5.667      0.000      -0.448      -0.218
ma.L3         -0.7404      0.038    -19.624      0.000      -0.814      -0.666
sigma2         0.0380      0.002     21.927      0.000       0.035       0.041
===================================================================================
Ljung-Box (L1) (Q):                   0.46   Jarque-Bera (JB):               262.75
Prob(Q):                              0.50   Prob(JB):                         0.00
Heteroskedasticity (H):               1.51   Skew:                            -0.76
Prob(H) (two-sided):                  0.00   Kurtosis:                         5.87
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).
"""

In [34]:
import statsmodels.api as sm

arima_model = sm.tsa.arima.ARIMA(train['Total_Production'], order=(3, 1, 3))
arima_model = arima_model.fit()
arima_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                               SARIMAX Results                                
==============================================================================
Dep. Variable:       Total_Production   No. Observations:                  579
Model:                 ARIMA(3, 1, 3)   Log Likelihood                 156.147
Date:                Sat, 29 Apr 2023   AIC                           -298.293
Time:                        12:00:11   BIC                           -267.776
Sample:                    01-31-1973   HQIC                          -286.394
                         - 03-31-2021                                         
Covariance Type:                  opg                                         
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
ar.L1         -1.5049      0.050    -29.809      0.000      -1.604      -1.406
ar.L2         -0.6070      0.088     -6.913      0.000      -0.779      -0.435
ar.L3          0.2266      0.051      4.465      0.000       0.127       0.326
ma.L1          0.9869      0.066     14.903      0.000       0.857       1.117
ma.L2         -0.2470      0.069     -3.585      0.000      -0.382      -0.112
ma.L3         -0.7265      0.063    -11.519      0.000      -0.850      -0.603
sigma2         0.0334      0.002     13.999      0.000       0.029       0.038
===================================================================================
Ljung-Box (L1) (Q):                   0.11   Jarque-Bera (JB):               299.68
Prob(Q):                              0.75   Prob(JB):                         0.00
Heteroskedasticity (H):               1.52   Skew:                            -0.77
Prob(H) (two-sided):                  0.00   Kurtosis:                         6.17
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).
"""

In [35]:
start = len(train)
end = len(train) + len(test) - 1
pred_arima = arima_model.predict(start=start, end=end, type='levels')
# print(prediction)

In [36]:
fig = px.line(test['Total_Production'], width=1500)
fig.add_scatter(x=test.index, y=pred_arima, name='Predictions')
fig.show()

In [37]:
print('Mean Squared Error: ', mean_squared_error(test['Total_Production'], pred_arima))

Mean Squared Error:  0.3838041979700952


<div style="border-radius: 10px; background-color: #112241">
    <h1 style="color: white; padding: 1rem"><b><span style='color:#8EDCE6'></span></b> LSTM Neural Network Model </b></h1>
</div>

In [38]:
train_l = total_production[:570]
test_l = total_production[570:]

In [39]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [40]:
scaler.fit(train)
scaled_train = scaler.transform(train)
scaled_test = scaler.transform(test)

In [41]:
from keras.preprocessing.sequence import TimeseriesGenerator

KeyboardInterrupt: 

In [ ]:
n_input = 3
n_features = 1
generator = TimeseriesGenerator(scaled_train, scaled_train, length=n_input, batch_size=1)

In [ ]:
n_input = 12
generator = TimeseriesGenerator(scaled_train, scaled_train, length=n_input, batch_size=1)

In [ ]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM

In [ ]:
# define model
model = Sequential()
model.add(LSTM(100, activation='relu', input_shape=(n_input, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

In [ ]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_4 (LSTM)               (None, 100)               40800     
                                                                 
 dense_2 (Dense)             (None, 1)                 101       
                                                                 
Total params: 40,901
Trainable params: 40,901
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# fit model
model.fit(generator,epochs=100)

Epoch 1/100
567/567 [==============================] - 3s 3ms/step - loss: 0.0117
Epoch 2/100
567/567 [==============================] - 2s 3ms/step - loss: 0.0048
Epoch 3/100
567/567 [==============================] - 2s 3ms/step - loss: 0.0039
Epoch 4/100
567/567 [==============================] - 2s 3ms/step - loss: 0.0034
Epoch 5/100
567/567 [==============================] - 2s 3ms/step - loss: 0.0036
Epoch 6/100
567/567 [==============================] - 2s 4ms/step - loss: 0.0034
Epoch 7/100
567/567 [==============================] - 2s 4ms/step - loss: 0.0034
Epoch 8/100
567/567 [==============================] - 2s 4ms/step - loss: 0.0036
Epoch 9/100
567/567 [==============================] - 2s 4ms/step - loss: 0.0033
Epoch 10/100
567/567 [==============================] - 2s 4ms/step - loss: 0.0032
Epoch 11/100
567/567 [==============================] - 2s 4ms/step - loss: 0.0032
Epoch 12/100
567/567 [==============================] - 2s 4ms/step - loss: 0.0030
Epoch 13/100


In [ ]:
loss_per_epoch = model.history.history['loss']
fig = px.line(loss_per_epoch).show()

In [ ]:
last_train_batch = scaled_train[-12:]
last_train_batch = last_train_batch.reshape((1, n_input, n_features))

In [ ]:
model.predict(last_train_batch)

1/1 [==============================] - 0s 187ms/step


array([[0.86121476]], dtype=float32)

In [ ]:
test_predictions = []

first_eval_batch = scaled_train[-n_input:]
current_batch = first_eval_batch.reshape((1, n_input, n_features))

for i in range(len(test)):
    
    # get the prediction value for the first batch
    current_pred = model.predict(current_batch)[0]
    
    # append the prediction into the array
    test_predictions.append(current_pred) 
    
    # use the prediction to update the batch and remove the first value
    current_batch = np.append(current_batch[:,1:,:],[[current_pred]],axis=1)

1/1 [==============================] - 0s 32ms/step


In [ ]:
test_predictions

[array([0.86121476], dtype=float32),
 array([0.83245933], dtype=float32),
 array([0.8694246], dtype=float32),
 array([0.91329396], dtype=float32),
 array([0.9470625], dtype=float32),
 array([0.94390726], dtype=float32),
 array([0.960631], dtype=float32),
 array([0.98129714], dtype=float32),
 array([1.054083], dtype=float32),
 array([1.1193308], dtype=float32),
 array([0.76469374], dtype=float32),
 array([1.081523], dtype=float32),
 array([1.0561452], dtype=float32),
 array([1.0183706], dtype=float32),
 array([1.0469966], dtype=float32),
 array([1.0495499], dtype=float32),
 array([1.050457], dtype=float32),
 array([1.0362124], dtype=float32),
 array([1.0178951], dtype=float32),
 array([0.9942225], dtype=float32)]

In [ ]:
test

Total_Production
Date                        
2021-04-30          8.017904
2021-05-31          8.400589
2021-06-30          8.170063
2021-07-31          8.357812
2021-08-31          8.421374
2021-09-30          8.066687
2021-10-31          8.371038
2021-11-30          8.348218
2021-12-31          8.672236
2022-01-31          8.531384
2022-02-28          7.765558
2022-03-31          8.679065
2022-04-30          8.308820
2022-05-31          8.725353
2022-06-30          8.570749
2022-07-31          8.771935
2022-08-31          8.810077
2022-09-30          8.558521
2022-10-31          8.760568
2022-11-30          8.619915

In [ ]:
true_predictions = scaler.inverse_transform(test_predictions)

In [ ]:
test['Predictions'] = true_predictions
test

Total_Production  Predictions
Date                                     
2021-04-30          8.017904     8.159312
2021-05-31          8.400589     8.030679
2021-06-30          8.170063     8.196037
2021-07-31          8.357812     8.392280
2021-08-31          8.421374     8.543338
2021-09-30          8.066687     8.529224
2021-10-31          8.371038     8.604035
2021-11-30          8.348218     8.696482
2021-12-31          8.672236     9.022078
2022-01-31          8.531384     9.313954
2022-02-28          7.765558     7.727540
2022-03-31          8.679065     9.144826
2022-04-30          8.308820     9.031303
2022-05-31          8.725353     8.862324
2022-06-30          8.570749     8.990378
2022-07-31          8.771935     9.001800
2022-08-31          8.810077     9.005858
2022-09-30          8.558521     8.942137
2022-10-31          8.760568     8.860197
2022-11-30          8.619915     8.754301

In [ ]:
# test.plot(figsize=(14,5))

fig = px.line(test).show()

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, accuracy_score
from math import sqrt
rmse=sqrt(mean_squared_error(test['Total_Production'],test['Predictions']))
r2 = (r2_score(test['Total_Production'], test['Predictions']))
print(rmse)
print(r2)

0.35351186429064174
-0.6687586684531786


<div style="border-radius: 10px; background-color: #112241">
    <h1 style="color: white; padding: 1rem"><b><span style='color:#8EDCE6'></span></b> Analysis of Consumption </b></h1>
</div>

In [ ]:
consumption = pd.read_csv('Updated/Consumption_Total.csv')
consumption.head()

Continent               Country         1980         1981         1982  \
0    Africa               Algeria  0.780695167  0.663391323  0.952188116   
1    Africa                Angola  0.058366148  0.057863688  0.062007899   
2    Africa                 Benin  0.006526525  0.006574612  0.004640112   
3    Africa              Botswana  0.014748762  0.015462338  0.014427219   
4    Africa          Burkina Faso    0.0060363  0.006019807  0.006019807   

          1983         1984         1985         1986         1987  ...  \
0  1.070561843  1.130786713  1.046418247  1.066300962  1.138318654  ...   
1  0.066297007  0.059894701  0.073766696  0.072853256  0.075135479  ...   
2  0.006731564  0.006673241  0.007698814  0.007501055  0.005942365  ...   
3  0.014460824  0.014444631  0.018865991  0.020060806  0.021144246  ...   
4  0.006019807    0.0060363  0.005819147  0.006886218  0.007191413  ...   

          2013         2014         2015         2016         2017  \
0  2.037584643  2.299888436   2.35214754   2.33598238  2.365986905   
1  0.347761278  0.382763726   0.39921871  0.364251517  0.347458949   
2  0.066471109  0.070275151  0.077723341  0.094785008   0.10051639   
3  0.065375734  0.065661654  0.080008274  0.088008537  0.080969008   
4    0.0451141  0.042012755  0.053396002  0.051306252   0.05946458   

          2018         2019         2020         2021 Total_Consumption  
0  2.522119152  2.624873096  2.480810774  2.581123314         64.746181  
1  0.359226946  0.404865374  0.402317536  0.328628418          7.403765  
2  0.111506331  0.101325936  0.108653617  0.110194887          1.660207  
3  0.080276228  0.080755726  0.076835026  0.082892488          2.021542  
4  0.066130673  0.067697934  0.064550875  0.068226015          0.988877  

[5 rows x 45 columns]

In [ ]:
top_consumption = consumption[['Country', 'Total_Consumption']].sort_values(by=['Total_Consumption'], ascending=False).head(10)
# top_production.head(10)

fig = px.bar(top_consumption, x='Country', y='Total_Consumption',labels={
                     "Country": "Countries",
                     "Total_production": "Total Consumption"
                 },title='Top 10 Countries with the Highest Energy Consumption:', width=1500, height=700)
fig.show()

In [ ]:
continent_consumption =  consumption.groupby(by='Continent')['Total_Consumption'].sum()
print(continent_consumption)

fig = px.pie(consumption, values='Total_Consumption', names='Continent',color='Continent',
             title='Continent-wise total consumption of the World',
             width=1500, height=700)
fig.show()

Continent
Africa                      559.693585
Asia & Oceania             5890.712088
Central & South America     858.645159
Eurasia                    2015.012531
Europe                     3387.844503
Middle East                 873.845333
North America              4614.115501
Name: Total_Consumption, dtype: float64


In [ ]:
top_consumption1 = consumption[['Country', 'Total_Consumption']].sort_values(by=['Total_Consumption'], ascending=False).head(10)
top_consumption2 = consumption[consumption.Country.isin(top_consumption1['Country'].unique())].sort_values(by=['Total_Consumption'], ascending=False).head(10)
top_consumption2 = top_consumption2.T
top_consumption2.drop(['Country', 'Total_Consumption', 'Continent'], axis=0, inplace=True)
top_consumption2.index.name = 'Year'
top_consumption2.columns = top_consumption1['Country'].values
top_consumption3 = top_consumption2.replace('--', 0)
top_consumption4 = top_consumption3.astype(float).round(2)
# top_consumption4.head(5)

fig = px.line(top_consumption4, x = top_consumption4.index, y= top_consumption4.columns[0:],labels={
                     "Year": "Year",
                     "value": "Consumption Rate"}, title='Consumption Rates of top 5 Countries',width=1500, height=700)
fig.show()

In [ ]:
coal_consumption = pd.read_csv('Updated/Consumption_Coal.csv')
NaturalGas_consumption = pd.read_csv('Updated/Consumption_NaturalGas.csv')
Neuclear_consumption = pd.read_csv('Updated/Consumption_NeuclearTot.csv')
Petrolium_consumption = pd.read_csv('Updated/Consumption_Petroleum.csv')

In [ ]:
coal_c = coal_consumption[['Country', 'Consumption_Coal', 'Continent']].sort_values(by=['Consumption_Coal'], ascending=False)
coal_c.head()
coal_c = coal_c.head(5)
print(colored('Top 5 Countries consuming energy from Coal: ', attrs=['bold']))
print('-------'*6)
coal_c.head()

Top 5 Countries consuming energy from Coal: 
------------------------------------------


Country  Consumption_Coal       Continent
65                     China       2028.909255  Asia & Oceania
171            United States        776.197063   North America
72                     India        323.207035  Asia & Oceania
220          Former U.S.S.R.        181.694862         Eurasia
74                     Japan        163.888517  Asia & Oceania

In [ ]:
naturalGas_c = NaturalGas_consumption[['Country', 'Consumption_NaturalGas', 'Continent']].sort_values(by=['Consumption_NaturalGas'], ascending=False)
naturalGas_c.head()
naturalGas_c = naturalGas_c.head(5)
print(colored('Top 5 Countries producing energy from Natural Gas: ', attrs=['bold']))
print('-------'*7)
naturalGas_c.head()

Top 5 Countries producing energy from Natural Gas: 
-------------------------------------------------


Country  Consumption_NaturalGas      Continent
171            United States              974.735990  North America
225                   Russia              459.280938        Eurasia
220          Former U.S.S.R.              246.591268        Eurasia
107                     Iran              138.961773    Middle East
166                   Canada              131.661210  North America

In [ ]:
neuclear_c = Neuclear_consumption[['Country', 'Consumption_Neuclear', 'Continent']].sort_values(by=['Consumption_Neuclear'], ascending=False)
neuclear_c.head()
neuclear_c = neuclear_c.head(5)
print(colored('Top 5 Countries producing energy from Neuclear resources: ', attrs=['bold']))
print('-------'*8)
neuclear_c.head()

Top 5 Countries producing energy from Neuclear resources: 
--------------------------------------------------------


Country  Consumption_Neuclear                Continent
171          United States            598.666180            North America
65                   China            254.473640           Asia & Oceania
166                 Canada            179.503929            North America
187                 France            172.336895                   Europe
127                 Brazil            139.072179  Central & South America

In [ ]:
petrolium_c = Petrolium_consumption[['Country', 'Consumption_Petrolium', 'Continent']].sort_values(by=['Consumption_Petrolium'], ascending=False)
petrolium_c.head()
petrolium_c = petrolium_c.head(5)
print(colored('Top 5 Countries producing energy from Petrolium: ', attrs=['bold']))
print('-------'*7)
petrolium_c.head()

Top 5 Countries producing energy from Petrolium: 
-------------------------------------------------


Country  Consumption_Petrolium       Continent
171            United States            1496.863866   North America
65                     China             542.168574  Asia & Oceania
74                     Japan             412.801150  Asia & Oceania
220          Former U.S.S.R.             224.171550         Eurasia
72                     India             202.301875  Asia & Oceania

In [ ]:
fig = make_subplots(rows=2, cols=2, subplot_titles=("Coal", "Natural Gas", "Neuclear Resources", "Petrolium"))

fig.add_trace(
    go.Bar(x=coal_c.Country, y=coal_c.Consumption_Coal),
                 row=1, col=1
)
fig.add_trace(
    go.Bar(x=naturalGas_c.Country, y=naturalGas_c.Consumption_NaturalGas),
                 row=1, col=2
)
fig.add_trace(
    go.Bar(x=neuclear_c.Country, y=neuclear_c.Consumption_Neuclear),
                 row=2, col=1
)
fig.add_trace(
    go.Bar(x=petrolium_c.Country, y=petrolium_c.Consumption_Petrolium),
                 row=2, col=2
)

fig.update_layout(height=1000, width=1500, title_text="Analysis of Consumption from Natural Resources")
fig.show()

In [ ]:
total_consumption0 = data3.filter(['Total Primary Energy Consumption'], axis=1)
total_consumption = total_consumption0.rename(columns={'Total Primary Energy Consumption':'Total_Consumption'})
total_consumption.head()

Total_Consumption
Date                         
1973-01-31           7.223873
1973-02-28           6.592366
1973-03-31           6.521439
1973-04-30           5.941729
1973-05-31           6.071940

<div style="border-radius: 10px; background-color: #112241">
    <h1 style="color: white; padding: 1rem"><b><span style='color:#8EDCE6'></span></b> Time Series Analysis of Consumption </b></h1>
</div>

In [ ]:
fig = px.line(total_consumption, x = total_consumption.index, y= total_consumption.Total_Consumption,labels={
                     "Month": "Month",
                     "value": "Production Rate"}, title='Monthly Poroduction Rate of World',width=1500, height=800)
fig.show()

In [ ]:
# from statsmodels.tsa.seasonal import seasonal_decompose
result_c = seasonal_decompose(total_consumption['Total_Consumption'])

fig_1 = px.line(y=result_c.observed, x=result_c.observed.index, title='Observed',width=1500)
fig_1.show()

In [ ]:
fig_2 = px.line(y=result_c.trend, x=result_c.trend.index, title='Trend',width=1500)
fig_2.show()

In [ ]:
fig_2 = px.line(y=result_c.seasonal, x=result_c.seasonal.index, title='Seasonality',width=1500)
fig_2.show()

In [ ]:
fig_2 = px.line(y=result_c.resid, x=result_c.resid.index, title='Residual',width=1500)
fig_2.show()

In [ ]:
train_c = total_consumption[:-20]
test_c = total_consumption[-20:]
print(train.shape, test.shape)

(579, 1) (20, 2)


In [ ]:
autoreg_model_c = AutoReg(train_c, lags=10).fit()
print(autoreg_model_c.summary())

                            AutoReg Model Results                             
Dep. Variable:      Total_Consumption   No. Observations:                  579
Model:                    AutoReg(10)   Log Likelihood                -237.640
Method:               Conditional MLE   S.D. of innovations              0.367
Date:                Sat, 22 Apr 2023   AIC                            499.280
Time:                        16:16:23   BIC                            551.407
Sample:                    11-30-1973   HQIC                           519.620
                         - 03-31-2021                                         
                            coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------
const                     0.2636      0.142      1.850      0.064      -0.016       0.543
Total_Consumption.L1      0.7674      0.039     19.786      0.000       0.691       0.843
Total_Co

In [ ]:
pred_auto_c = autoreg_model_c.predict(start = len(train_c), end = len(total_consumption)-1, dynamic=False)
# print(pred_auto)

In [ ]:
fig = px.line(test_c['Total_Consumption'], width=1500)
fig.add_scatter(x=test_c.index, y=pred_auto_c, name='Predictions')
fig.show()

In [ ]:
print('Mean Squared Error: ', mean_squared_error(test_c['Total_Consumption'], pred_auto_c))

Mean Squared Error:  0.1783805171630797


In [ ]:
from pmdarima import auto_arima
import warnings
warnings.filterwarnings("ignore")

In [ ]:
stepwise_fit_c = auto_arima(total_consumption['Total_Consumption'], trace=True, suppress_warnings=True)
stepwise_fit_c.summary()

Performing stepwise search to minimize aic
 ARIMA(2,1,2)(0,0,0)[0] intercept   : AIC=762.811, Time=0.60 sec
 ARIMA(0,1,0)(0,0,0)[0] intercept   : AIC=910.776, Time=0.05 sec
 ARIMA(1,1,0)(0,0,0)[0] intercept   : AIC=909.851, Time=0.05 sec
 ARIMA(0,1,1)(0,0,0)[0] intercept   : AIC=908.843, Time=0.07 sec
 ARIMA(0,1,0)(0,0,0)[0]             : AIC=908.783, Time=0.03 sec
 ARIMA(1,1,2)(0,0,0)[0] intercept   : AIC=761.780, Time=0.42 sec
 ARIMA(0,1,2)(0,0,0)[0] intercept   : AIC=781.471, Time=0.22 sec
 ARIMA(1,1,1)(0,0,0)[0] intercept   : AIC=775.207, Time=0.26 sec
 ARIMA(1,1,3)(0,0,0)[0] intercept   : AIC=722.314, Time=0.38 sec
 ARIMA(0,1,3)(0,0,0)[0] intercept   : AIC=721.187, Time=0.22 sec
 ARIMA(0,1,4)(0,0,0)[0] intercept   : AIC=719.927, Time=0.38 sec
 ARIMA(1,1,4)(0,0,0)[0] intercept   : AIC=685.109, Time=0.75 sec
 ARIMA(2,1,4)(0,0,0)[0] intercept   : AIC=667.524, Time=0.80 sec
 ARIMA(2,1,3)(0,0,0)[0] intercept   : AIC=688.744, Time=0.82 sec
 ARIMA(3,1,4)(0,0,0)[0] intercept   : AIC=658.3

<class 'statsmodels.iolib.summary.Summary'>
"""
                               SARIMAX Results                                
==============================================================================
Dep. Variable:                      y   No. Observations:                  599
Model:               SARIMAX(5, 1, 4)   Log Likelihood                -217.288
Date:                Sat, 22 Apr 2023   AIC                            454.575
Time:                        16:16:43   BIC                            498.511
Sample:                    01-31-1973   HQIC                           471.681
                         - 11-30-2022                                         
Covariance Type:                  opg                                         
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
ar.L1          0.1277      0.094      1.361      0.173      -0.056       0.312
ar.L2          0.7879      0.073     10.860      0.000       0.646       0.930
ar.L3         -0.1036      0.037     -2.818      0.005      -0.176      -0.032
ar.L4         -0.5414      0.040    -13.466      0.000      -0.620      -0.463
ar.L5          0.5085      0.069      7.412      0.000       0.374       0.643
ma.L1         -0.1575      0.085     -1.857      0.063      -0.324       0.009
ma.L2         -1.3327      0.066    -20.082      0.000      -1.463      -1.203
ma.L3         -0.3097      0.052     -5.948      0.000      -0.412      -0.208
ma.L4          0.8404      0.070     11.964      0.000       0.703       0.978
sigma2         0.1215      0.008     15.217      0.000       0.106       0.137
===================================================================================
Ljung-Box (L1) (Q):                   0.11   Jarque-Bera (JB):                11.06
Prob(Q):                              0.74   Prob(JB):                         0.00
Heteroskedasticity (H):               1.31   Skew:                             0.33
Prob(H) (two-sided):                  0.06   Kurtosis:                         2.90
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).
"""

In [ ]:
arima_model_c = sm.tsa.arima.ARIMA(train_c['Total_Consumption'], order=(5, 1, 4))
arima_model_c = arima_model_c.fit()
arima_model_c.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                               SARIMAX Results                                
==============================================================================
Dep. Variable:      Total_Consumption   No. Observations:                  579
Model:                 ARIMA(5, 1, 4)   Log Likelihood                -211.449
Date:                Sat, 22 Apr 2023   AIC                            442.898
Time:                        16:16:44   BIC                            486.494
Sample:                    01-31-1973   HQIC                           459.897
                         - 03-31-2021                                         
Covariance Type:                  opg                                         
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
ar.L1          0.1163      0.063      1.844      0.065      -0.007       0.240
ar.L2          0.8143      0.046     17.800      0.000       0.725       0.904
ar.L3         -0.1178      0.039     -3.052      0.002      -0.193      -0.042
ar.L4         -0.6272      0.038    -16.661      0.000      -0.701      -0.553
ar.L5          0.4314      0.054      7.983      0.000       0.326       0.537
ma.L1         -0.1750      0.052     -3.391      0.001      -0.276      -0.074
ma.L2         -1.3038      0.046    -28.278      0.000      -1.394      -1.213
ma.L3         -0.2510      0.042     -6.046      0.000      -0.332      -0.170
ma.L4          0.8269      0.044     18.793      0.000       0.741       0.913
sigma2         0.1211      0.008     14.480      0.000       0.105       0.137
===================================================================================
Ljung-Box (L1) (Q):                   0.45   Jarque-Bera (JB):                 9.43
Prob(Q):                              0.50   Prob(JB):                         0.01
Heteroskedasticity (H):               1.51   Skew:                             0.31
Prob(H) (two-sided):                  0.00   Kurtosis:                         2.86
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).
"""

In [ ]:
start = len(train_c)
end = len(train_c) + len(test_c) - 1
pred_arima_c = arima_model_c.predict(start=start, end=end, type='levels')
# print(prediction)

In [ ]:
fig = px.line(test_c['Total_Consumption'], width=1500)
fig.add_scatter(x=test_c.index, y=pred_arima_c, name='Predictions')
fig.show()

In [ ]:
print('Mean Squared Error: ', mean_squared_error(test_c['Total_Consumption'], pred_arima_c))

Mean Squared Error:  0.5381217362683925


In [ ]:
scaler = MinMaxScaler()
scaler.fit(train_c)
scaled_train_c = scaler.transform(train_c)
scaled_test_c = scaler.transform(test_c)

In [ ]:
n_input = 3
n_features = 1
generator = TimeseriesGenerator(scaled_train, scaled_train, length=n_input, batch_size=1)

In [ ]:
n_input = 12
generator = TimeseriesGenerator(scaled_train, scaled_train, length=n_input, batch_size=1)

In [ ]:
model = Sequential()
model.add(LSTM(100, activation='relu', input_shape=(n_input, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

In [ ]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_5 (LSTM)               (None, 100)               40800     
                                                                 
 dense_3 (Dense)             (None, 1)                 101       
                                                                 
Total params: 40,901
Trainable params: 40,901
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(generator,epochs=100)

Epoch 1/100
567/567 [==============================] - 4s 4ms/step - loss: 0.0148
Epoch 2/100
567/567 [==============================] - 2s 4ms/step - loss: 0.0044
Epoch 3/100
567/567 [==============================] - 2s 4ms/step - loss: 0.0036
Epoch 4/100
567/567 [==============================] - 2s 4ms/step - loss: 0.0038
Epoch 5/100
567/567 [==============================] - 2s 4ms/step - loss: 0.0038
Epoch 6/100
567/567 [==============================] - 2s 4ms/step - loss: 0.0032
Epoch 7/100
567/567 [==============================] - 3s 5ms/step - loss: 0.0033
Epoch 8/100
567/567 [==============================] - 2s 4ms/step - loss: 0.0033
Epoch 9/100
567/567 [==============================] - 2s 4ms/step - loss: 0.0033
Epoch 10/100
567/567 [==============================] - 2s 4ms/step - loss: 0.0032
Epoch 11/100
567/567 [==============================] - 2s 4ms/step - loss: 0.0032
Epoch 12/100
567/567 [==============================] - 2s 4ms/step - loss: 0.0029
Epoch 13/100


In [ ]:
loss_per_epoch = model.history.history['loss']
fig = px.line(loss_per_epoch).show()


In [ ]:
last_train_batch = scaled_train[-12:]
last_train_batch = last_train_batch.reshape((1, n_input, n_features))


In [ ]:
model.predict(last_train_batch)

1/1 [==============================] - 0s 233ms/step


array([[0.86226165]], dtype=float32)

In [ ]:
test_predictions = []

first_eval_batch = scaled_train[-n_input:]
current_batch = first_eval_batch.reshape((1, n_input, n_features))

for i in range(len(test)):
    
    # get the prediction value for the first batch
    current_pred = model.predict(current_batch)[0]
    
    # append the prediction into the array
    test_predictions.append(current_pred) 
    
    # use the prediction to update the batch and remove the first value
    current_batch = np.append(current_batch[:,1:,:],[[current_pred]],axis=1)

1/1 [==============================] - 0s 28ms/step


In [ ]:
true_predictions = scaler.inverse_transform(test_predictions)


In [ ]:
test_c['Predictions'] = true_predictions
test_c


Total_Consumption  Predictions
Date                                      
2021-04-30           7.526169     9.081849
2021-05-31           7.731281     8.919124
2021-06-30           8.050457     9.009312
2021-07-31           8.418050     9.171460
2021-08-31           8.528827     9.300515
2021-09-30           7.724445     9.279756
2021-10-31           7.758761     9.317611
2021-11-30           8.144297     9.341543
2021-12-31           8.753643     9.466312
2022-01-31           9.508195     9.869132
2022-02-28           8.460574     8.748991
2022-03-31           8.543246     9.644588
2022-04-30           7.746131     9.624826
2022-05-31           7.935685     9.574335
2022-06-30           8.155757     9.625497
2022-07-31           8.584805     9.666615
2022-08-31           8.530444     9.692689
2022-09-30           7.782741     9.691278
2022-10-31           7.811175     9.704803
2022-11-30           8.285891     9.585251

In [ ]:
fig = px.line(test_c).show()

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, accuracy_score
from math import sqrt
rmse=sqrt(mean_squared_error(test['Total_Production'],test['Predictions']))
print(rmse)
print('R2 Score: ', r2_score(test['Total_Production'], test['Predictions']))

0.35351186429064174
R2 Score:  -0.6687586684531786
