In [1]:
import numpy as np
import pandas as pd 
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

 DATA COLLECTION & PRE-PROCESSING 

In [2]:
anime_data=pd.read_csv(r'D:\Users\User\Downloads\mal_top2000_anime.csv')

In [3]:
anime_data.head()

Unnamed: 0                                Name Type  Score  Score Rank  \
0           0    Fullmetal Alchemist: Brotherhood   TV   9.14           1   
1           1                        Spy x Family   TV   9.09           2   
2           2  Shingeki no Kyojin Season 3 Part 2   TV   9.08           3   
3           3                         Steins;Gate   TV   9.08           4   
4           4                            Gintama°   TV   9.08           5   

   Popularity Rank                     Air Date  \
0                3   Apr 5, 2009 to Jul 4, 2010   
1              350             Apr 9, 2022 to ?   
2               32  Apr 29, 2019 to Jul 1, 2019   
3               13  Apr 6, 2011 to Sep 14, 2011   
4              335  Apr 8, 2015 to Mar 30, 2016   

                                      Studio  Num. of episodes  \
0                                  ['Bones']                64   
1  ['Wit Studio', '            CloverWorks']                12   
2                             ['Wit Studio']                10   
3                              ['White Fox']                24   
4                  ['Bandai Namco Pictures']                51   

                                        Genres  \
0  ['Action', 'Adventure', 'Drama', 'Fantasy']   
1                         ['Action', 'Comedy']   
2                          ['Action', 'Drama']   
3              ['Drama', 'Sci-Fi', 'Suspense']   
4               ['Action', 'Comedy', 'Sci-Fi']   

                                           Theme(s) Demographic  
0                                      ['Military']     Shounen  
1                                     ['Childcare']     Shounen  
2                  ['Gore', 'Military', 'Survival']     Shounen  
3                  ['Psychological', 'Time Travel']        None  
4  ['Gag Humor', 'Historical', 'Parody', 'Samurai']     Shounen

In [4]:
anime_data=anime_data.rename(columns={'Unnamed: 0':'Index'})
print(anime_data)

      Index                                              Name     Type  Score  \
0         0                  Fullmetal Alchemist: Brotherhood       TV   9.14   
1         1                                      Spy x Family       TV   9.09   
2         2                Shingeki no Kyojin Season 3 Part 2       TV   9.08   
3         3                                       Steins;Gate       TV   9.08   
4         4                                          Gintama°       TV   9.08   
...     ...                                               ...      ...    ...   
1995   1995                                Shugo Chara!! Doki       TV   7.41   
1996   1996  Steins;Gate: Soumei Eichi no Cognitive Computing      ONA   7.41   
1997   1997                   Taiho Shichau zo: Second Season       TV   7.41   
1998   1998            Tanaka-kun wa Itsumo Kedaruge Specials  Special   7.41   
1999   1999              Tiger & Bunny Movie 1: The Beginning    Movie   7.41   

      Score Rank  Popularit

In [5]:
anime_data.head()

Index                                Name Type  Score  Score Rank  \
0      0    Fullmetal Alchemist: Brotherhood   TV   9.14           1   
1      1                        Spy x Family   TV   9.09           2   
2      2  Shingeki no Kyojin Season 3 Part 2   TV   9.08           3   
3      3                         Steins;Gate   TV   9.08           4   
4      4                            Gintama°   TV   9.08           5   

   Popularity Rank                     Air Date  \
0                3   Apr 5, 2009 to Jul 4, 2010   
1              350             Apr 9, 2022 to ?   
2               32  Apr 29, 2019 to Jul 1, 2019   
3               13  Apr 6, 2011 to Sep 14, 2011   
4              335  Apr 8, 2015 to Mar 30, 2016   

                                      Studio  Num. of episodes  \
0                                  ['Bones']                64   
1  ['Wit Studio', '            CloverWorks']                12   
2                             ['Wit Studio']                10   
3                              ['White Fox']                24   
4                  ['Bandai Namco Pictures']                51   

                                        Genres  \
0  ['Action', 'Adventure', 'Drama', 'Fantasy']   
1                         ['Action', 'Comedy']   
2                          ['Action', 'Drama']   
3              ['Drama', 'Sci-Fi', 'Suspense']   
4               ['Action', 'Comedy', 'Sci-Fi']   

                                           Theme(s) Demographic  
0                                      ['Military']     Shounen  
1                                     ['Childcare']     Shounen  
2                  ['Gore', 'Military', 'Survival']     Shounen  
3                  ['Psychological', 'Time Travel']        None  
4  ['Gag Humor', 'Historical', 'Parody', 'Samurai']     Shounen

In [6]:
anime_data.shape

(2000, 12)

In [7]:
anime_data['Score'] = anime_data['Score'].astype(str)

In [8]:
selected_features = ['Score','Genres','Demographic','Theme(s)']
print(selected_features)

['Score', 'Genres', 'Demographic', 'Theme(s)']


In [9]:
for feature in selected_features:
    anime_data[feature] = anime_data[feature].fillna('')

In [10]:
combined_feature = anime_data['Score']+' '+anime_data['Genres']+' '+anime_data['Demographic']+' '+anime_data['Theme(s)']

In [11]:
print(combined_feature)

0       9.14 ['Action', 'Adventure', 'Drama', 'Fantasy...
1         9.09 ['Action', 'Comedy'] Shounen ['Childcare']
2       9.08 ['Action', 'Drama'] Shounen ['Gore', 'Mil...
3       9.08 ['Drama', 'Sci-Fi', 'Suspense'] None ['Ps...
4       9.08 ['Action', 'Comedy', 'Sci-Fi'] Shounen ['...
                              ...                        
1995    7.41 ['Comedy'] Shoujo ['Mahou Shoujo', 'School']
1996              7.41 ['Comedy', 'Sci-Fi'] None ['None']
1997    7.41 ['Action', 'Comedy'] Shounen ['Detective'...
1998    7.41 ['Comedy', 'Slice of Life'] None ['Iyashi...
1999    7.41 ['Action', 'Comedy', 'Mystery'] None ['Ad...
Length: 2000, dtype: object


In [12]:
#converting text data to feature vectors 
#creation of an instance 
vectorizer= TfidfVectorizer()
feature_vectors = vectorizer.fit_transform(combined_feature)
print(feature_vectors)

  (0, 138)	0.40920869783963004
  (0, 164)	0.26141736705442
  (0, 111)	0.27981423619012935
  (0, 108)	0.25112100653373204
  (0, 92)	0.28814433134935596
  (0, 90)	0.228364925700642
  (0, 12)	0.6983364090025104
  (1, 100)	0.6078461656126801
  (1, 102)	0.21084195008002088
  (1, 8)	0.6855337520879978
  (1, 164)	0.2566247816775907
  (1, 90)	0.22417829335931871
  (2, 174)	0.516023374465725
  (2, 118)	0.4505849991126486
  (2, 7)	0.5391648022405205
  (2, 138)	0.3383684733896387
  (2, 164)	0.2161620607644289
  (2, 108)	0.20764815622318203
  (2, 90)	0.18883149770034313
  (3, 178)	0.42572202739159964
  (3, 177)	0.42572202739159964
  (3, 151)	0.32247538563427297
  (3, 142)	0.12576687374004972
  (3, 175)	0.37885380953513387
  (3, 113)	0.23194259763210684
  :	:
  (1996, 159)	0.3867381972535449
  (1996, 102)	0.26463154488848895
  (1997, 36)	0.5428148762878683
  (1997, 107)	0.4911889216650361
  (1997, 183)	0.5479616942089537
  (1997, 102)	0.21296956770591663
  (1997, 164)	0.25921439635593935
  (1997, 9

COSINE SIMILARITY 
- getting similarity scores using cosine similarity


In [13]:
similarity = cosine_similarity(feature_vectors)
print(similarity)
print(similarity.shape)

[[1.         0.11828063 0.29023914 ... 0.11947421 0.         0.04540368]
 [0.11828063 1.         0.09780446 ... 0.1621868  0.04677797 0.08399724]
 [0.29023914 0.09780446 1.         ... 0.09879141 0.         0.03754361]
 ...
 [0.11947421 0.1621868  0.09879141 ... 1.         0.35420184 0.34355357]
 [0.         0.04677797 0.         ... 0.35420184 1.         0.33705001]
 [0.04540368 0.08399724 0.03754361 ... 0.34355357 0.33705001 1.        ]]
(2000, 2000)


USER INPUT FOR ANIME 

In [14]:
anime_name = input('Enter your favorite Anime:')


Enter your favorite Anime:kimi no na wa


In [15]:
#creating a list with all anime names from the dataset 
list_anime_titles = anime_data['Name'].tolist()
print(list_anime_titles)

['Fullmetal Alchemist: Brotherhood', 'Spy x Family', 'Shingeki no Kyojin Season 3 Part 2', 'Steins;Gate', 'Gintama°', "Gintama'", 'Gintama: The Final', 'Hunter x Hunter (2011)', 'Fruits Basket: The Final', "Gintama': Enchousen", 'Ginga Eiyuu Densetsu', 'Gintama.', 'Kaguya-sama wa Kokurasetai: Ultra Romantic', '3-gatsu no Lion 2nd Season', 'Koe no Katachi', 'Gintama', 'Violet Evergarden Movie', 'Clannad: After Story', 'Gintama Movie 2: Kanketsu-hen - Yorozuya yo Eien Nare', 'Code Geass: Hangyaku no Lelouch R2', 'Owarimonogatari 2nd Season', 'Shingeki no Kyojin: The Final Season Part 2', 'Kimetsu no Yaiba: Yuukaku-hen', 'Gintama.: Shirogane no Tamashii-hen - Kouhan-sen', 'Kimi no Na wa.', 'Shingeki no Kyojin: The Final Season', 'Monster', 'Mob Psycho 100 II', 'Gintama.: Shirogane no Tamashii-hen', 'Kizumonogatari III: Reiketsu-hen', 'Shiguang Dailiren', 'Sen to Chihiro no Kamikakushi', 'Haikyuu!!: Karasuno Koukou vs. Shiratorizawa Gakuen Koukou', 'Kingdom 3rd Season', 'Monogatari Series:

In [16]:
# find the closest match for the anime provided by the user 
find_cl_match = difflib.get_close_matches(anime_name,list_anime_titles)
print(find_cl_match)

['Kimi no Na wa.', 'Kyoukai no Kanata']


In [17]:
close_match = find_cl_match[0]
print(close_match)

Kimi no Na wa.


In [18]:
#finding the index of anime with the title 
index_of_anime = anime_data[anime_data.Name == close_match]['Index'].values[0]
print(index_of_anime)

24


In [19]:
#getting a list of similar anime 
similarity_score = list(enumerate(similarity[index_of_anime]))
print(similarity_score)

[(0, 0.052310816646287096), (1, 0.0), (2, 0.04325502186003453), (3, 0.05641084848993502), (4, 0.0), (5, 0.0), (6, 0.03645285154622627), (7, 0.02665884062620755), (8, 0.1447931379040876), (9, 0.0), (10, 0.06290930384795546), (11, 0.0), (12, 0.5272696851274081), (13, 0.035711097246111496), (14, 0.629243687796046), (15, 0.0), (16, 0.10219131365641458), (17, 0.16554912610539285), (18, 0.0), (19, 0.06307970571227318), (20, 0.1248827075389088), (21, 0.051359543274066), (22, 0.0), (23, 0.0), (24, 1.0000000000000002), (25, 0.04348670624775556), (26, 0.04187782393447158), (27, 0.10179996119051432), (28, 0.0), (29, 0.12431609364074118), (30, 0.16678171626943764), (31, 0.0665513597376445), (32, 0.0), (33, 0.0), (34, 0.09659417285558955), (35, 0.021351716037397366), (36, 0.06397448933666294), (37, 0.025932654453846734), (38, 0.03659664952291141), (39, 0.05628870288031251), (40, 0.0), (41, 0.05622655610812011), (42, 0.07480181238279524), (43, 0.151226105215372), (44, 0.03717722319056564), (45, 0.05

In [20]:
len(similarity_score)

2000

In [21]:
#sorting anime based on their similarity score
sorted_similar_anime = sorted(similarity_score , key =lambda x:x[1], reverse= True)
print(sorted_similar_anime)

[(24, 1.0000000000000002), (1217, 0.7011127319169846), (14, 0.629243687796046), (165, 0.60955174865806), (753, 0.5635840898800293), (225, 0.5474258629808774), (750, 0.5430562273486531), (1496, 0.5346382948988656), (64, 0.5341771471472228), (1885, 0.5337302736292653), (12, 0.5272696851274081), (1611, 0.518051344899673), (111, 0.511729401353467), (494, 0.5094281052401475), (1058, 0.5075506309164792), (454, 0.48950594605388914), (754, 0.4888324563581728), (1124, 0.4799240409373019), (756, 0.478790439334888), (573, 0.452315216724489), (758, 0.44083901479296256), (755, 0.41892980959212234), (895, 0.4132591213622715), (580, 0.41240773240556344), (762, 0.40940307805466575), (760, 0.399625512819302), (757, 0.39849448335482407), (763, 0.3962900366178293), (761, 0.37707346891176263), (759, 0.3753296391534627), (764, 0.3439266187659882), (1336, 0.3406414680329535), (752, 0.33732343718590685), (751, 0.32249896744723494), (711, 0.2742315363453424), (117, 0.2687285463931556), (1683, 0.24821615878700

In [22]:
# print the name of similar anime based on the Index
print('Anime Suggested for you :) \n')

i=1
for anime in sorted_similar_anime:
    Index=anime[0]
    title_from_index = anime_data[anime_data.Index==Index]['Name'].values[0]
    if(i<20):
        print(i,'.',title_from_index)
        i+=1

Anime Suggested for you :) 

1 . Kimi no Na wa.
2 . Shinigami Bocchan to Kuro Maid
3 . Koe no Katachi
4 . Kaguya-sama wa Kokurasetai: Tensai-tachi no Renai Zunousen
5 . Durarara!! Specials
6 . Komi-san wa, Comyushou desu. 2nd Season
7 . Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai. Movie
8 . Kaguya-sama wa Kokurasetai: Tensai-tachi no Renai Zunousen OVA
9 . Kaguya-sama wa Kokurasetai? Tensai-tachi no Renai Zunousen
10 . Guilty Crown
11 . Kaguya-sama wa Kokurasetai: Ultra Romantic
12 . Karakai Jouzu no Takagi-san: Water Slide
13 . Karakai Jouzu no Takagi-san 3
14 . Komi-san wa, Comyushou desu.
15 . Karakai Jouzu no Takagi-san
16 . Karakai Jouzu no Takagi-san 2
17 . High☆Speed! Movie: Free! Starting Days
18 . Senpai ga Uzai Kouhai no Hanashi
19 . Kyoukai no Kanata Movie: I'll Be Here - Kako-hen - Yakusoku no Kizuna


ANIME RECOMMENDATION SYSTEM 

In [23]:
anime_name = input('Enter your favorite Anime:')
list_anime_titles = anime_data['Name'].tolist()
find_cl_match = difflib.get_close_matches(anime_name,list_anime_titles)
close_match = find_cl_match[0]
index_of_anime = anime_data[anime_data.Name == close_match]['Index'].values[0]
similarity_score = list(enumerate(similarity[index_of_anime]))
sorted_similar_anime = sorted(similarity_score , key =lambda x:x[1], reverse= True)
print('Anime Suggested for you :) \n')

i=1
for anime in sorted_similar_anime:
    Index=anime[0]
    title_from_index = anime_data[anime_data.Index==Index]['Name'].values[0]
    demog_from_index = anime_data[anime_data.Index==Index]['Demographic'].values[0]
    if(i<20):
        print(i,'.',title_from_index, ([demog_from_index]))
        i+=1


Enter your favorite Anime:No game no Life
Anime Suggested for you :) 

1 . No Game No Life ['None']
2 . Tsukimonogatari ['None']
3 . Black Clover ['Shounen']
4 . Quanzhi Gaoshou Zhi Dianfeng Rongyao ['None']
5 . Yu☆Gi☆Oh! Duel Monsters ['Shounen']
6 . D-Frag! ['Seinen']
7 . Yu☆Gi☆Oh! 5D's ['Shounen']
8 . Hikaru no Go: Hokuto Hai e no Michi ['Shounen']
9 . Shoubushi Densetsu Tetsuya ['Shounen']
10 . Hikaru no Go ['Shounen']
11 . Yu☆Gi☆Oh! The Dark Side of Dimensions ['Shounen']
12 . Zero no Tsukaima F ['None']
13 . Saki ['None']
14 . Saki Zenkoku-hen ['None']
15 . Pokemon Generations ['Kids']
16 . Saki Achiga-hen: Episode of Side-A Specials ['None']
17 . Shion no Ou ['None']
18 . Uchouten Kazoku 2 ['None']
19 . Shinchou Yuusha: Kono Yuusha ga Ore Tueee Kuse ni Shinchou Sugiru ['None']


GUI CREATION


In [25]:
import tkinter as tk
from tkinter import messagebox
import difflib
from PIL import ImageTk, Image


#create Tkinter GUI 
root=tk.Tk()
root.title("Anime Recommendation System")
root.configure(bg="#222222")
root.columnconfigure(0, weight=1)
root.rowconfigure(0, weight=1)
root.rowconfigure(1,weight=1)






#define styling
title_font=("Arial",16,"bold")
root.option_add("*Font",title_font)

#define styling for labels
label_font=("Arial",12,"bold")
entry_font=("Arial",12)
button_font=("Arial",12,"bold")
button_bg="#3366CC"
button_fg="#FFFFFF"
button_active_bg="#25476D"
button_active_fg="#FFFFFF"

#create a canvas widget and set the bg image
try:
    bg_image=Image.open(r"D:\Users\User\Downloads\ani.gif")
    bg_image=bg_image.resize((1300,600),Image.ANTIALIAS)
    root.background=ImageTk.PhotoImage(bg_image)
    
    #create a canvas widget and place the bg on it
    canvas=tk.Canvas(root, width=900, height=400)
    canvas.grid(row=0,column=0,padx=10,pady=10,sticky="nsew")
    canvas.create_image(0,0,anchor=tk.NW,image=root.background)
except IOError:
    messagebox.showerror("Error","failed to load background image.")
    
    
#Create GUI elements - label for anime name input 
name_label=tk.Label(root,text="Enter Anime Name:")
name_label.grid(row=0, column=0,padx=10,pady=10,sticky="w")




#create the entry field
entry = tk.Entry(root, font=entry_font)
entry.grid(row=0, column=1, padx=10, pady=10 , sticky="ew")



def get_recommendations():
    anime_name=entry.get()
    

#find closest match in the anime dataset
    list_anime_titles = anime_data['Name'].tolist()
    find_cl_match = difflib.get_close_matches(anime_name, list_anime_titles)
    if find_cl_match:
        close_match = find_cl_match[0]
        index_of_anime = anime_data[anime_data.Name == close_match]['Index'].values[0]

        # Compute similarity scores
        similarity_score = list(enumerate(similarity[index_of_anime]))
        sorted_similar_anime = sorted(similarity_score , key=lambda x: x[1], reverse=True)

        # Generate recommendations
        recommendations = []
        for i, anime in enumerate(sorted_similar_anime):
            if i < 20:
                Index = anime[0]
                title_from_index = anime_data[anime_data.Index == Index]['Name'].values[0]
                demog_from_index = anime_data[anime_data.Index == Index]['Demographic'].values[0]
                recommendations.append(f"{i+1}. {title_from_index} {demog_from_index}")
      
        messagebox.showinfo("Anime Recommendations For You :)","\n".join(recommendations))
    
    else:
        messagebox.showinfo("Anime Recommendations For You","No match found :(")

button = tk.Button(root, text="Get Recommendations",font=button_font, bg=button_bg, fg=button_fg,activebackground=button_active_bg, activeforeground=button_active_fg, command=get_recommendations)
button.grid(row=1, column=0 , padx=10 ,pady=10, sticky="ew")




#start the event loop
root.mainloop()
