In [71]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns

In [72]:
dataset = pd.read_csv('/content/EEG_Eye_State_Classification.csv')

In [73]:
dataset.head()

AF3       F7       F3      FC5       T7       P7       O1       O2  \
0  4329.23  4009.23  4289.23  4148.21  4350.26  4586.15  4096.92  4641.03   
1  4324.62  4004.62  4293.85  4148.72  4342.05  4586.67  4097.44  4638.97   
2  4327.69  4006.67  4295.38  4156.41  4336.92  4583.59  4096.92  4630.26   
3  4328.72  4011.79  4296.41  4155.90  4343.59  4582.56  4097.44  4630.77   
4  4326.15  4011.79  4292.31  4151.28  4347.69  4586.67  4095.90  4627.69   

        P8       T8      FC6       F4       F8      AF4  eyeDetection  
0  4222.05  4238.46  4211.28  4280.51  4635.90  4393.85             0  
1  4210.77  4226.67  4207.69  4279.49  4632.82  4384.10             0  
2  4207.69  4222.05  4206.67  4282.05  4628.72  4389.23             0  
3  4217.44  4235.38  4210.77  4287.69  4632.31  4396.41             0  
4  4210.77  4244.10  4212.82  4288.21  4632.82  4398.46             0

In [74]:
#checking null value is there in dataset
dataset.isna().sum()

AF3             0
F7              0
F3              0
FC5             0
T7              0
P7              0
O1              0
O2              0
P8              0
T8              0
FC6             0
F4              0
F8              0
AF4             0
eyeDetection    0
dtype: int64

In [75]:
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [76]:
print(x)

[[4329.23 4009.23 4289.23 ... 4280.51 4635.9  4393.85]
 [4324.62 4004.62 4293.85 ... 4279.49 4632.82 4384.1 ]
 [4327.69 4006.67 4295.38 ... 4282.05 4628.72 4389.23]
 ...
 [4277.44 3990.77 4246.67 ... 4257.95 4591.79 4339.49]
 [4284.62 3991.79 4251.28 ... 4267.18 4596.41 4350.77]
 [4287.69 3997.44 4260.   ... 4274.36 4597.95 4350.77]]


In [77]:
print(y)

[0 0 0 ... 1 1 1]


In [78]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2 ,random_state = 2)

In [79]:
#Feature scaling of x variable

In [80]:

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [81]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB  
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from xgboost import XGBClassifier
#to find accuracy 
from sklearn.metrics import accuracy_score, precision_score

In [82]:
svc = SVC(kernel = 'sigmoid',gamma = 1.0)
rfc = RandomForestClassifier(n_estimators = 50, random_state = 2)
lr = LogisticRegression(solver = 'liblinear')
knn = KNeighborsClassifier()
dtc = DecisionTreeClassifier(max_depth = 5)
gnb = GaussianNB()
adc = AdaBoostClassifier(n_estimators = 50, random_state = 2)
bc = BaggingClassifier(n_estimators = 50, random_state = 2)
etc = ExtraTreesClassifier(n_estimators = 50, random_state = 2)
xbg = XGBClassifier(n_estimators = 50, random_state = 2)

In [83]:
classifier = {
    'SVM': svc,
    'RandomForestClassifier' : rfc,
    'Logistic_Regression': lr,
    'KNN': knn,
    'Decision Tree': dtc,
    'Gaussian Naive Bayes': gnb,
    'AdaBoost': adc,
    'Bagging': bc,
    'ExtraTree': etc,
    'XGB': xbg
}

In [84]:
def train_classifier(classifier,x_train,x_test,y_train,y_test):
  classifier.fit(x_train,y_train)
  y_pred = classifier.predict(x_test)
  accuracy = accuracy_score(y_test,y_pred)
  precision = precision_score(y_test,y_pred)
  return accuracy ,precision 

In [85]:
accuracy_score1 = []
precision_score2 = []
for name,clsr in classifier.items():
  current_accuracy,current_precision = train_classifier(clsr,x_train,x_test,y_train,y_test)
  print("Model - ", name)
  print("Accuracy - ", current_accuracy)
  print("Precision - ", current_precision)
  print("\n")
  accuracy_score1.append(current_accuracy)
  precision_score2.append(current_precision)

Model -  SVM
Accuracy -  0.5146862483311081
Precision -  0.4540622627182992


Model -  RandomForestClassifier
Accuracy -  0.9168891855807744
Precision -  0.9221183800623053


Model -  Logistic_Regression
Accuracy -  0.5947930574098799
Precision -  0.5702479338842975


Model -  KNN
Accuracy -  0.8317757009345794
Precision -  0.8156892612338157


Model -  Decision Tree
Accuracy -  0.6779038718291055
Precision -  0.6735849056603773


Model -  Gaussian Naive Bayes
Accuracy -  0.4432576769025367
Precision -  0.44261733470366565


Model -  AdaBoost
Accuracy -  0.735981308411215
Precision -  0.7199675324675324


Model -  Bagging
Accuracy -  0.9122162883845126
Precision -  0.9205974842767296


Model -  ExtraTree
Accuracy -  0.9389185580774366
Precision -  0.9570747217806042


Model -  XGB
Accuracy -  0.9082109479305741
Precision -  0.9069230769230769




In [86]:
performance_dp = pd.DataFrame({'Algorithm ':classifier.keys(),'Accuracy ':accuracy_score1,'Precision':precision_score2})

In [87]:
performance_dp

Algorithm   Accuracy   Precision
0                     SVM   0.514686   0.454062
1  RandomForestClassifier   0.916889   0.922118
2     Logistic_Regression   0.594793   0.570248
3                     KNN   0.831776   0.815689
4           Decision Tree   0.677904   0.673585
5    Gaussian Naive Bayes   0.443258   0.442617
6                AdaBoost   0.735981   0.719968
7                 Bagging   0.912216   0.920597
8               ExtraTree   0.938919   0.957075
9                     XGB   0.908211   0.906923

In [88]:
#we can see that our extratree classifier is the best model


In [89]:
import pickle
pickle.dump(etc,open('/content/model.pkl','wb'))

In [90]:
model_loaded = pickle.load(open('/content/model.pkl','rb'))

In [91]:
y_pred = model_loaded.predict(x_test)
print(y_pred)

[1 0 1 ... 1 0 1]


In [96]:
#confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print("Confusion matrix is \n",cm)
print("\nAccuracy of our model is ",accuracy_score(y_test,y_pred))

Confusion matrix is 
 [[1609   54]
 [ 129 1204]]

Accuracy of our model is  0.9389185580774366
